import Link from "next/link";
import { Pencil } from "lucide-react";
import { Button } from "@/components/common/button";
import { NOTICE_PRIORITY_LABEL, PUBLICATION_STATUS_LABEL, PUBLICATION_TYPE_LABEL, SERVICE_CATEGORY_LABEL, formatPublicationDate } from "./publication-display";
export function PublicationDetails({ publication }: { publication: Publication }) {
    const rows: [string, string][] = [["ID", publication.id.toString()], ["Tipo", PUBLICATION_TYPE_LABEL[publication.type]], ["Status", PUBLICATION_STATUS_LABEL[publication.status]], ["Criada em", formatPublicationDate(publication.createdAt)], ["Atualizada em", formatPublicationDate(publication.updatedAt)], ["Publicada em", formatPublicationDate(publication.publishedAt)]];
    if (publication.type === "event") rows.push(["Início", formatPublicationDate(publication.startAt)], ["Término", formatPublicationDate(publication.endAt)], ["ID do endereço", publication.addressId.toString()], ["Participantes", publication.maxParticipants?.toString() ?? "Sem limite"], ["Exige confirmação", publication.requiresConfirmation ? "Sim" : "Não"]);
    if (publication.type === "notice") rows.push(["Expiração", formatPublicationDate(publication.expiresAt)], ["Prioridade", NOTICE_PRIORITY_LABEL[publication.noticePriority]]);
    if (publication.type === "service") rows.push(["Categoria", SERVICE_CATEGORY_LABEL[publication.serviceCategory]]);
    return <div className="flex flex-col gap-5"><section className="rounded-2xl border border-j-gray-200 bg-j-white p-6 shadow-sm"><div className="mb-5 flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-2xl font-black text-j-blue-800">{publication.title}</h1>{publication.summary && <p className="mt-1 text-j-gray-600">{publication.summary}</p>}</div><Link href={`/admin/publications/${publication.id.toString()}/edit`}><Button><Pencil size={16} /> Editar</Button></Link></div><div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">{rows.map(([key, value]) => <div key={key}><dt className="text-xs font-bold uppercase text-j-gray-400">{key}</dt><dd className="mt-1 text-sm font-semibold text-j-gray-700">{value}</dd></div>)}</div></section><section className="rounded-2xl border border-j-gray-200 bg-j-white p-6 shadow-sm"><h2 className="mb-3 font-black text-j-blue-800">Conteúdo</h2><p className="whitespace-pre-wrap text-j-gray-700">{publication.content}</p></section>{publication.media.length > 0 && <section className="rounded-2xl border border-j-gray-200 bg-j-white p-6 shadow-sm"><h2 className="mb-3 font-black text-j-blue-800">Mídias</h2><ul className="space-y-2">{publication.media.map((media) => <li key={media.id.toString()} className="rounded-lg bg-j-gray-100 p-3 text-sm"><a href={media.url} target="_blank" rel="noreferrer" className="font-bold text-j-blue-700 underline">{media.caption || media.alt || media.url}</a> <span className="text-j-gray-500">({media.type === "image" ? "Imagem" : "Vídeo"})</span></li>)}</ul></section>}</div>;
}
