import { createMockPublicationsRepository } from "@/mocks/admin/publications";
const baseQuery: PublicationListQuery = { page: 0, size: 10 };
const service: CreatePublicationInput = { type: "service", title: "Serviço de teste", content: "Conteúdo", status: "draft", media: [], serviceCategory: "general" };
describe("mock de publicações", () => {
    it("filtra por tipo e status", async () => { const repo = createMockPublicationsRepository({ delay: 0 }); const result = await repo.list({ ...baseQuery, type: "notice", status: "published" }); expect(result.content.length).toBeGreaterThan(0); expect(result.content.every((p) => p.type === "notice" && p.status === "published")).toBe(true); });
    it("busca sem diferenciar acentos e maiúsculas", async () => { const repo = createMockPublicationsRepository({ delay: 0 }); const result = await repo.list({ ...baseQuery, q: "EXPEDICAO" }); expect(result.content[0]?.title).toContain("Expedição"); });
    it("pagina e ordena", async () => { const repo = createMockPublicationsRepository({ delay: 0 }); const page = await repo.list({ page: 1, size: 5, sort: "title,asc" }); expect(page.number).toBe(1); expect(page.content).toHaveLength(5); const sorted = await repo.list({ page: 0, size: 100, sort: "title,asc" }); expect(sorted.content.map((p) => p.title)).toEqual([...sorted.content.map((p) => p.title)].sort((a, b) => a.localeCompare(b, "pt-BR"))); });
    it("cria, atualiza e exclui", async () => { const repo = createMockPublicationsRepository({ delay: 0 }); const created = await repo.create(service); expect(created.id).toBeGreaterThan(BigInt(12)); const updated = await repo.update(created.id, { ...service, title: "Serviço atualizado", status: "published" }); expect(updated.title).toBe("Serviço atualizado"); expect(updated.publishedAt).toBeDefined(); await repo.delete(created.id); await expect(repo.get(created.id)).rejects.toThrow("não encontrada"); });
    it("rejeita consulta, edição e exclusão inexistentes", async () => { const repo = createMockPublicationsRepository({ delay: 0 }); await expect(repo.get(BigInt(999))).rejects.toThrow("não encontrada"); await expect(repo.update(BigInt(999), service)).rejects.toThrow("não encontrada"); await expect(repo.delete(BigInt(999))).rejects.toThrow("não encontrada"); });
});
