'use client';
import { useMutation,useQueryClient } from '@tanstack/react-query';
import { useFormContext } from 'react-hook-form';
import toast from 'react-hot-toast';
import { UserPlus,X } from 'lucide-react';
import { createDependentAction,updateDependentAction } from '@/actions/dependents';
import { Button,ButtonIcon } from '@/components/common/button';
import { Form } from '@/components/common/form';
import { InputCheckbox } from '@/components/common/input/input-checkbox';
import { InputDate } from '@/components/common/input/input-date';
import { InputRegister } from '@/components/common/input/input-register';
import { SelectRegister } from '@/components/common/select/select-register';
import { TextareaRegister } from '@/components/common/textarea/textarea-register';
import { useModal } from '@/providers/ModalProvider';
import { createDependentFormSchema,editDependentFormSchema } from '@/schemas/dependents';
import { maskCPF,unMaskCPF } from '@/utils/masks/maskCPF';
import { maskPhoneNumber,unMaskPhoneNumber } from '@/utils/masks/maskPhoneNumber';
const light='[&_label]:!text-j-gray-700 [&_input]:!border-j-gray-200 [&_input]:!bg-j-gray-100 [&_input]:!text-j-gray-700 [&_select]:!border-j-gray-200 [&_select]:!bg-j-gray-100 [&_select]:!text-j-gray-700 [&_textarea]:!border-j-gray-200 [&_textarea]:!bg-j-gray-100 [&_textarea]:!text-j-gray-700';
function Fields({isEdit}:{isEdit:boolean}){const {formState}=useFormContext<CreateMemberDependentFormData>();return <><section className="w-full"><h3 className="mb-3 font-extrabold text-j-blue-800">Dados pessoais</h3><div className={`grid gap-4 md:grid-cols-2 ${light}`}><InputRegister name="name" label="Nome completo" required/><InputRegister name="cpf" label="CPF" mask={maskCPF} inputMode="numeric" disabled={isEdit} required/><InputDate name="birthDate" label="Data de nascimento" max={new Date().toISOString().slice(0,10)} required/><SelectRegister name="relationshipType" label="Parentesco" required><option value="">Selecione</option><option value="CHILD">Filho(a)</option><option value="SPOUSE">Cônjuge</option><option value="PARENT">Pai/Mãe</option><option value="SIBLING">Irmão/Irmã</option><option value="GUEST">Convidado(a)</option><option value="OTHER">Outro</option></SelectRegister><InputRegister name="phoneNumber" label="Telefone" mask={maskPhoneNumber} inputMode="tel" required/></div></section><section className="w-full border-t border-j-gray-200 pt-5"><h3 className="mb-3 font-extrabold text-j-blue-800">Perfil médico</h3><div className={`grid gap-4 md:grid-cols-2 ${light}`}><SelectRegister name="medicalProfile.bloodType" label="Tipo sanguíneo" required><option value="">Selecione</option>{['A+','A-','B+','B-','AB+','AB-','O+','O-'].map(t=><option key={t}>{t}</option>)}</SelectRegister><InputRegister name="medicalProfile.allergies" label="Alergias"/><InputRegister name="medicalProfile.chronicDiseases" label="Doenças crônicas"/><InputRegister name="medicalProfile.medications" label="Medicamentos"/><TextareaRegister name="medicalProfile.medicalNotes" label="Observações médicas"/></div></section><div className="w-full rounded-2xl bg-blue-50 p-4"><InputCheckbox name="consentAccepted" label="Confirmo que tenho autorização para cadastrar e tratar os dados deste dependente." className="[&_span:last-child]:!text-j-gray-700 [&_span:first-of-type]:!bg-j-white"/>{formState.errors.consentAccepted&&<p className="mt-2 text-sm text-j-red-400">{formState.errors.consentAccepted.message}</p>}</div><Button type="submit" disabled={formState.isSubmitting} className="w-full bg-j-blue-700 text-j-white hover:bg-j-blue-800 hover:text-j-white">{formState.isSubmitting?'Salvando...':'Salvar dependente'}</Button></>}
export function CreateDependentModal({dependent}:{dependent?:MemberDependent}){const {setClose}=useModal();const qc=useQueryClient();const isEdit=!!dependent;const mutation=useMutation({mutationFn:(payload:CreateMemberDependentRequest)=>isEdit?updateDependentAction(dependent.id,payload):createDependentAction(payload),onSuccess:()=>{toast.success(isEdit?'Dependente atualizado com sucesso!':'Dependente cadastrado com sucesso!');qc.invalidateQueries({queryKey:['dependents']});setClose()},onError:(error)=>toast.error(error.message||(isEdit?'Erro ao editar dependente.':'Erro ao cadastrar dependente.'))});const submit=(data:CreateMemberDependentFormData)=>mutation.mutateAsync({...data,cpf:unMaskCPF(data.cpf),phoneNumber:unMaskPhoneNumber(data.phoneNumber)});const defaults:CreateMemberDependentFormData={name:dependent?.name??'',cpf:dependent?maskCPF(dependent.cpf):'',birthDate:dependent?.birthDate??'',relationshipType:dependent?.relationshipType as MemberDependentRelationshipType,phoneNumber:dependent?maskPhoneNumber(dependent.phoneNumber):'',medicalProfile:{bloodType:dependent?.medicalProfile.bloodType??'',allergies:dependent?.medicalProfile.allergies??'',chronicDiseases:dependent?.medicalProfile.chronicDiseases??'',medications:dependent?.medicalProfile.medications??'',medicalNotes:dependent?.medicalProfile.medicalNotes??''},consentAccepted:dependent?.consentAccepted??false};return <div className="relative flex max-h-[92dvh] w-full max-w-3xl flex-col overflow-y-auto rounded-3xl bg-j-white shadow-2xl"><ButtonIcon onClick={setClose} className="absolute right-4 top-4 z-10 rounded-full bg-j-gray-100 p-2"><X size={21}/></ButtonIcon><header className="border-b border-j-gray-200 px-5 py-6 pr-16 md:px-8"><div className="flex gap-4"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-j-blue-800 text-j-yellow-300"><UserPlus size={20}/></span><div><h2 className="text-xl font-extrabold text-j-blue-800">{isEdit?'Editar dependente':'Incluir dependente'}</h2><p className="text-sm text-j-gray-500">{isEdit?'Atualize os dados da pessoa vinculada.':'Cadastre uma pessoa vinculada à sua associação.'}</p></div></div></header><Form<CreateMemberDependentFormData> schema={isEdit?editDependentFormSchema:createDependentFormSchema} onSubmit={submit} onError={()=>undefined} formOptions={{defaultValues:defaults}} className="gap-5 px-5 py-5 md:px-8"><Fields isEdit={isEdit}/></Form></div>}