'use client';

import { CalendarDays,HeartPulse,IdCard,Phone,ShieldCheck,UserRound,X } from 'lucide-react';
import { ButtonIcon } from '@/components/common/button';
import { maskCPF } from '@/utils/masks/maskCPF';
import { maskDate } from '@/utils/masks/maskDate';
import { maskPhoneNumber } from '@/utils/masks/maskPhoneNumber';
import { useModal } from '@/providers/ModalProvider';

const RELATIONSHIP_LABELS:Record<MemberDependentRelationshipType,string>={CHILD:'Filho(a)',GUEST:'Convidado(a)',OTHER:'Outro',PARENT:'Pai/Mãe',SIBLING:'Irmão/Irmã',SPOUSE:'Cônjuge'};
const BLOOD_TYPES:Record<string,string>={A_POSITIVE:'A+',A_NEGATIVE:'A-',B_POSITIVE:'B+',B_NEGATIVE:'B-',AB_POSITIVE:'AB+',AB_NEGATIVE:'AB-',O_POSITIVE:'O+',O_NEGATIVE:'O-'};
const show=(value:string|null)=>value?.trim()||'Não se aplica';
function Detail({label,value,icon:Icon}:{label:string;value:string;icon:typeof IdCard}){return <div className="flex gap-3 rounded-xl bg-j-gray-100/70 p-3"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-j-white text-j-blue-700 shadow-sm"><Icon size={16}/></span><div className="min-w-0"><span className="text-[10px] font-bold uppercase tracking-wide text-j-gray-400">{label}</span><p className="break-words text-sm font-bold text-j-gray-700">{value}</p></div></div>}
export function ViewDependentModal({dependent}:{dependent:MemberDependent}){const {setClose}=useModal();return <div className="relative flex max-h-[92dvh] w-full max-w-2xl flex-col overflow-y-auto rounded-3xl bg-j-white shadow-2xl"><ButtonIcon onClick={setClose} className="absolute right-4 top-4 z-10 rounded-full bg-j-gray-100 p-2 text-j-gray-600 hover:bg-j-gray-200 md:right-6 md:top-6"><X size={21}/></ButtonIcon><header className="border-b border-j-gray-200 bg-gradient-to-r from-blue-50 to-j-white px-5 py-6 pr-16 md:px-8"><div className="flex gap-4"><span className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-j-blue-800 text-j-yellow-300"><UserRound size={22}/></span><div className="min-w-0"><h2 className="truncate text-xl font-extrabold text-j-blue-800">{dependent.name}</h2><span className="mt-1 inline-flex rounded-full bg-j-white px-2.5 py-1 text-xs font-bold text-j-blue-700 shadow-sm">{RELATIONSHIP_LABELS[dependent.relationshipType]}</span></div></div></header><div className="flex flex-col gap-5 p-5 md:p-8"><section><h3 className="mb-3 font-extrabold text-j-blue-800">Dados pessoais</h3><div className="grid gap-3 sm:grid-cols-2"><Detail icon={IdCard} label="CPF" value={maskCPF(dependent.cpf)}/><Detail icon={CalendarDays} label="Nascimento" value={maskDate(dependent.birthDate)}/><Detail icon={Phone} label="Telefone" value={maskPhoneNumber(dependent.phoneNumber)}/><Detail icon={ShieldCheck} label="Consentimento" value={dependent.consentAccepted?'Aceito':'Pendente'}/></div></section><section className="border-t border-j-gray-200 pt-5"><div className="mb-3 flex items-center gap-2"><HeartPulse size={18} className="text-red-500"/><h3 className="font-extrabold text-j-blue-800">Perfil médico</h3></div><div className="grid gap-3 sm:grid-cols-2"><Detail icon={HeartPulse} label="Tipo sanguíneo" value={BLOOD_TYPES[dependent.medicalProfile.bloodType??'']??show(dependent.medicalProfile.bloodType)}/><Detail icon={HeartPulse} label="Alergias" value={show(dependent.medicalProfile.allergies)}/><Detail icon={HeartPulse} label="Doenças crônicas" value={show(dependent.medicalProfile.chronicDiseases)}/><Detail icon={HeartPulse} label="Medicamentos" value={show(dependent.medicalProfile.medications)}/><div className="sm:col-span-2"><Detail icon={HeartPulse} label="Observações médicas" value={show(dependent.medicalProfile.medicalNotes)}/></div></div></section></div></div>}